name: aqi-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pymongo>=4.5.0
    - python-dotenv>=1.0.0
    - requests>=2.31.0
    - numpy>=1.24.0
    - pandas>=2.0.0
    - scikit-learn>=1.3.0
    - joblib>=1.3.0
    - mlflow>=2.8.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - streamlit>=1.28.0
    - certifi>=2023.7.22